[package]
name = "sheet-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sheet = { path = "../sheet" }
tokio = { version = "1", features = ["full"] }
sinfonia-sdk = { path = "../sdk" }
